baseURL = 'https://dcx7c5.github.io'
languageCode = 'en-us'
title = "DCx's Blog"
theme = "LoveIt"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[author]
  name = "DCx7c5"
  link = "https://dcx7c5.github.io"

[params]
  defaultTheme = "dark"
  title = "DCx's Blog"
  description = "Welcome to DCx's Blog"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      logo = ""
      name = "DCx's Blog"


  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
#    author = "asdasds"
    since = 2023

  [params.app]
    title = "DCx's Blog"

  [params.home]
    
    [params.home.profile]
      enable = true
      social = true
      title = "DCx7c5"
      subtitle = "Welcome to my blog"

  [params.social]
    GitHub = "DCx7c5"
    Twitter = "dcx7c5"
    Discord = "dcx7c5"


[markup]

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

  [markup.goldmark]

    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = ":year/:month/:filename"

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
