baseURL = 'https://dcx7c5.github.io'
languageCode = 'en-us'
title = "DCx's Blog"
theme = "LoveIt"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[author]
  name = "DCx7c5"
  link = "https://dcx7c5.github.io"

[params]
  defaultTheme = "dark"
  title = "DCx's Blog"
  description = "Welcome to DCx's Blog"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = ":year/:month/:filename"

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
